services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./R/data/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rstudio:
    build: .
    image: kojamad28/rstudio-db:latest
    container_name: rstudio
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.env
    ports:
     - "8787:8787"
    volumes:
     - ./R/data:/home/rstudio
    tty: true
    stdin_open: true
